In [ ]:
pip uninstall -y tensorflow tensorflow-cpu keras tf-keras tf-keras-nightly tensorboard absl-py

Found existing installation: tensorflow 2.20.0
Uninstalling tensorflow-2.20.0:
  Successfully uninstalled tensorflow-2.20.0
Found existing installation: keras 3.11.3
Uninstalling keras-3.11.3:
  Successfully uninstalled keras-3.11.3
Found existing installation: tf_keras 2.20.1
Uninstalling tf_keras-2.20.1:
  Successfully uninstalled tf_keras-2.20.1
Found existing installation: tensorboard 2.20.0
Uninstalling tensorboard-2.20.0:
  Successfully uninstalled tensorboard-2.20.0
Found existing installation: absl-py 2.3.1
Uninstalling absl-py-2.3.1:
  Successfully uninstalled absl-py-2.3.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\marku\anaconda3\Lib\site-packages\~-nsorflow'.
You can safely remove it manually.
WARNING: Skipping tensorflow-cpu as it is not installed.
WARNING: Skipping tf-keras-nightly as it is not installed.

In [ ]:
pip install -U "transformers[torch]" accelerate

Requirement already satisfied: accelerate in c:\users\marku\anaconda3\lib\site-packages (1.10.1)
Requirement already satisfied: transformers[torch] in c:\users\marku\anaconda3\lib\site-packages (4.57.0)
Requirement already satisfied: filelock in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (0.35.3)
Requirement already satisfied: numpy>=1.17 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (2024.9.11)
Requirement already satisfied: requests in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (2.32.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (4.66.5)
Requirement already satisfied: torch>=2.2 in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]) (2.8.0)
Requirement already satisfied: psutil in c:\users\marku\anaconda3\lib\site-packages (from accelerate) (7.1.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\marku\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers[torch]) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\marku\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers[torch]) (4.11.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\marku\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx in c:\users\marku\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (3.3)
Requirement already satisfied: jinja2 in c:\users\marku\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (3.1.4)
Requirement already satisfied: setuptools in c:\users\marku\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (75.1.0)
Requirement already satisfied: colorama in c:\users\marku\anaconda3\lib\site-packages (from tqdm>=4.27->transformers[torch]) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers[torch]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers[torch]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers[torch]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers[torch]) (2025.1.31)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\marku\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.2->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\marku\anaconda3\lib\site-packages (from jinja2->torch>=2.2->transformers[torch]) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip -q install -U transformers accelerate peft bitsandbytes optuna
!pip install -U ipywidgets==8.1.2 jupyterlab_widgets==3.0.13

Collecting ipywidgets==8.1.2
  Downloading ipywidgets-8.1.2-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab_widgets==3.0.13
  Using cached jupyterlab_widgets-3.0.13-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: comm>=0.1.3 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (8.27.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.10 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (4.0.14)
Requirement already satisfied: decorator in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (2.15.1)
Requirement already satisfied: stack-data in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.2.0)
Requirement already satisfied: colorama in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\marku\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.2) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\marku\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.2) (0.2.5)
Requirement already satisfied: executing in c:\users\marku\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (0.8.3)
Requirement already satisfied: asttokens in c:\users\marku\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\marku\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (0.2.2)
Requirement already satisfied: six in c:\users\marku\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (1.16.0)
Downloading ipywidgets-8.1.2-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.13-py3-none-any.whl (214 kB)
Installing collected packages: jupyterlab_widgets, ipywidgets
  Attempting uninstall: jupyterlab_widgets
    Found existing installation: jupyterlab_widgets 3.0.15
    Uninstalling jupyterlab_widgets-3.0.15:
      Successfully uninstalled jupyterlab_widgets-3.0.15
  Attempting uninstall: ipywidgets
    Found existing installation: ipywidgets 8.1.7
    Uninstalling ipywidgets-8.1.7:
      Successfully uninstalled ipywidgets-8.1.7
Successfully installed ipywidgets-8.1.2 jupyterlab_widgets-3.0.13

In [ ]:
!pip install -U ipywidgets==8.1.2 widgetsnbextension==4.0.10
!jupyter nbextension enable --py widgetsnbextension

Requirement already satisfied: ipywidgets==8.1.2 in c:\users\marku\anaconda3\lib\site-packages (8.1.2)
Collecting widgetsnbextension==4.0.10
  Downloading widgetsnbextension-4.0.10-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: comm>=0.1.3 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (8.27.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (5.14.3)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in c:\users\marku\anaconda3\lib\site-packages (from ipywidgets==8.1.2) (3.0.13)
Requirement already satisfied: decorator in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (2.15.1)
Requirement already satisfied: stack-data in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.2.0)
Requirement already satisfied: colorama in c:\users\marku\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.1.2) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\marku\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.2) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\marku\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.2) (0.2.5)
Requirement already satisfied: executing in c:\users\marku\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (0.8.3)
Requirement already satisfied: asttokens in c:\users\marku\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\marku\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (0.2.2)
Requirement already satisfied: six in c:\users\marku\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets==8.1.2) (1.16.0)
Downloading widgetsnbextension-4.0.10-py3-none-any.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ------------------ --------------------- 1.0/2.3 MB 7.2 MB/s eta 0:00:01
   ------------------------------------ --- 2.1/2.3 MB 7.3 MB/s eta 0:00:01
   ------------------------------------ --- 2.1/2.3 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 3.3 MB/s eta 0:00:00
Installing collected packages: widgetsnbextension
  Attempting uninstall: widgetsnbextension
    Found existing installation: widgetsnbextension 4.0.14
    Uninstalling widgetsnbextension-4.0.14:
      Successfully uninstalled widgetsnbextension-4.0.14
Successfully installed widgetsnbextension-4.0.10

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console dejavu events execute kernel kernelspec lab
labextension labhub migrate nbconvert notebook qtconsole run script server
troubleshoot trust

Jupyter command `jupyter-nbextension` not found.

In [ ]:
import ipywidgets as widgets
from IPython.display import display
display(widgets.VBox([widgets.IntSlider(), widgets.Text(value="hello")]))

VBox(children=(IntSlider(value=0), Text(value='hello')))

In [ ]:
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU device name:", torch.cuda.get_device_name(0))
    print("GPU count:", torch.cuda.device_count())
else:
    print("No GPU detected by PyTorch.")

PyTorch version: 2.5.1+cu121
CUDA available: True
GPU device name: NVIDIA GeForce RTX 3050 Laptop GPU
GPU count: 1

In [ ]:
pip uninstall -y transformers tokenizers

Found existing installation: transformers 4.57.0
Uninstalling transformers-4.57.0:
  Successfully uninstalled transformers-4.57.0
Found existing installation: tokenizers 0.22.1
Uninstalling tokenizers-0.22.1:
  Successfully uninstalled tokenizers-0.22.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\marku\anaconda3\Lib\site-packages\~-kenizers'.
You can safely remove it manually.

In [ ]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install "transformers[torch]==4.42.4" tokenizers==0.19.1 accelerate datasets peft optuna

Looking in indexes: https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch in c:\users\marku\anaconda3\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in c:\users\marku\anaconda3\lib\site-packages (0.20.1+cu121)
Requirement already satisfied: torchaudio in c:\users\marku\anaconda3\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: filelock in c:\users\marku\anaconda3\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\marku\anaconda3\lib\site-packages (from torch) (4.11.0)
Requirement already satisfied: networkx in c:\users\marku\anaconda3\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\users\marku\anaconda3\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in c:\users\marku\anaconda3\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: setuptools in c:\users\marku\anaconda3\lib\site-packages (from torch) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\marku\anaconda3\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\marku\anaconda3\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in c:\users\marku\anaconda3\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\marku\anaconda3\lib\site-packages (from torchvision) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\marku\anaconda3\lib\site-packages (from jinja2->torch) (2.1.3)
Collecting transformers==4.42.4 (from transformers[torch]==4.42.4)
  Using cached transformers-4.42.4-py3-none-any.whl.metadata (43 kB)
Collecting tokenizers==0.19.1
  Using cached tokenizers-0.19.1-cp312-none-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: accelerate in c:\users\marku\anaconda3\lib\site-packages (1.10.1)
Requirement already satisfied: datasets in c:\users\marku\anaconda3\lib\site-packages (3.5.0)
Requirement already satisfied: peft in c:\users\marku\anaconda3\lib\site-packages (0.17.1)
Requirement already satisfied: optuna in c:\users\marku\anaconda3\lib\site-packages (4.5.0)
Requirement already satisfied: filelock in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (0.35.3)
Requirement already satisfied: numpy<2.0,>=1.17 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (2024.9.11)
Requirement already satisfied: requests in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\marku\anaconda3\lib\site-packages (from transformers==4.42.4->transformers[torch]==4.42.4) (4.66.5)
Requirement already satisfied: torch in c:\users\marku\anaconda3\lib\site-packages (from transformers[torch]==4.42.4) (2.5.1+cu121)
Requirement already satisfied: psutil in c:\users\marku\anaconda3\lib\site-packages (from accelerate) (7.1.0)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\marku\anaconda3\lib\site-packages (from datasets) (16.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\marku\anaconda3\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\marku\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: xxhash in c:\users\marku\anaconda3\lib\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\marku\anaconda3\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in c:\users\marku\anaconda3\lib\site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in c:\users\marku\anaconda3\lib\site-packages (from datasets) (3.10.5)
Requirement already satisfied: alembic>=1.5.0 in c:\users\marku\anaconda3\lib\site-packages (from optuna) (1.13.3)
Requirement already satisfied: colorlog in c:\users\marku\anaconda3\lib\site-packages (from optuna) (6.9.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\marku\anaconda3\lib\site-packages (from optuna) (2.0.34)
Requirement already satisfied: Mako in c:\users\marku\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (1.2.3)
Requirement already satisfied: typing-extensions>=4 in c:\users\marku\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (4.11.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\marku\anaconda3\lib\site-packages (from aiohttp->datasets) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\marku\anaconda3\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\marku\anaconda3\lib\site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\marku\anaconda3\lib\site-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\marku\anaconda3\lib\site-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\marku\anaconda3\lib\site-packages (from aiohttp->datasets) (1.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers==4.42.4->transformers[torch]==4.42.4) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers==4.42.4->transformers[torch]==4.42.4) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers==4.42.4->transformers[torch]==4.42.4) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\marku\anaconda3\lib\site-packages (from requests->transformers==4.42.4->transformers[torch]==4.42.4) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\marku\anaconda3\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.0.1)
Requirement already satisfied: networkx in c:\users\marku\anaconda3\lib\site-packages (from torch->transformers[torch]==4.42.4) (3.3)
Requirement already satisfied: jinja2 in c:\users\marku\anaconda3\lib\site-packages (from torch->transformers[torch]==4.42.4) (3.1.4)
Requirement already satisfied: setuptools in c:\users\marku\anaconda3\lib\site-packages (from torch->transformers[torch]==4.42.4) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\marku\anaconda3\lib\site-packages (from torch->transformers[torch]==4.42.4) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\marku\anaconda3\lib\site-packages (from sympy==1.13.1->torch->transformers[torch]==4.42.4) (1.3.0)
Requirement already satisfied: colorama in c:\users\marku\anaconda3\lib\site-packages (from tqdm>=4.27->transformers==4.42.4->transformers[torch]==4.42.4) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marku\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\marku\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\marku\anaconda3\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\marku\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\marku\anaconda3\lib\site-packages (from jinja2->torch->transformers[torch]==4.42.4) (2.1.3)
Downloading transformers-4.42.4-py3-none-any.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.3 MB 8.4 MB/s eta 0:00:01
   -------------- ------------------------- 3.4/9.3 MB 9.6 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.3 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 11.2 MB/s eta 0:00:00
Downloading tokenizers-0.19.1-cp312-none-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 13.8 MB/s eta 0:00:00
Installing collected packages: tokenizers, transformers
Successfully installed tokenizers-0.19.1 transformers-4.42.4

In [ ]:
import sys, transformers, os, platform
print("Python:", sys.version)
print("Platform:", platform.platform())
print("Transformers version:", transformers.__version__)
print("Transformers location:", transformers.__file__)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

Python: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
Platform: Windows-11-10.0.26100-SP0
Transformers version: 4.42.4
Transformers location: C:\Users\marku\anaconda3\Lib\site-packages\transformers\__init__.py

In [ ]:
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")
model = model.to("cuda")
print(next(model.parameters()).device)

cuda:0

In [ ]:
import os, shutil, gc, torch, optuna
from huggingface_hub import login, notebook_login, HfFolder, HfApi, hf_hub_download, delete_repo, list_repo_files, snapshot_download
os.environ["TRANSFORMERS_NO_TF"] = "1"   # prevents TF/Keras import
#os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
from transformers import (AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig,
                          Trainer, TrainingArguments, default_data_collator)
from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training)
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
from datasets import load_dataset, concatenate_datasets
import json
import inspect
import pandas as pd
import tempfile
from datetime import datetime
from collections import Counter
from torch.utils.data import Dataset

In [ ]:
REPO_ID   = "eduhuemar001/tinyllama-german-sentiment-4bit-tuning-v3"
STUDY_DB  = "optuna_study.db"
STUDY_KEY = "optuna/optuna_study.db"
STUDY_NAME= "tinyllama_tuning_new_" + datetime.now().strftime("%Y%m%d_%H%M%S")
N_TRIALS  = 25

api = HfApi()

In [ ]:
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
try:
    fp = hf_hub_download(REPO_ID, STUDY_KEY, local_dir=".", local_dir_use_symlinks=False)
    if os.path.basename(fp) != STUDY_DB:
        shutil.copy(fp, STUDY_DB)
    print("Loaded existing Optuna DB from Hub.")
except Exception:
    print("No existing Optuna DB on Hub; starting fresh.")

storage = f"sqlite:///{STUDY_DB}"

C:\Users\marku\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:1212: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(

In [ ]:
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Load tokenizer once
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Decide compute dtype (T4: fp16; A100/H100: bf16)
USE_BF16 = torch.cuda.is_available() and torch.cuda.get_device_capability(0)[0] >= 8

compute_dtype = torch.bfloat16 if USE_BF16 else torch.float16
quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=compute_dtype
)

In [ ]:
def build_model(lora_dropout=0.05):
    # Detect GPU availability
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")

    # Load base model (4-bit or normal) and place it on the right device
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto" if device == "cuda" else None,  # auto maps layers to GPU
        quantization_config=quant_config if device == "cuda" else None,
    )

    # Prepare for k-bit LoRA training (handles gradient settings, etc.)
    model = prepare_model_for_kbit_training(model)
    model.config.use_cache = False

    # Define your LoRA config
    lora_config = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=lora_dropout,
        bias="none",
        task_type="CAUSAL_LM"
    )

    # Wrap the model with LoRA adapters
    model = get_peft_model(model, lora_config)

    # Make sure the model is on GPU explicitly
    if device == "cuda":
        model.to("cuda")

    return model

In [ ]:
# CONSTANTS
HF_DATASET_REPO_ID = "eduhuemar001/dataset-sentiment-4bit-train-tuning-v3"
HF_DATASET_REPO_ID_TEST = "eduhuemar001/dataset-sentiment-4bit-test-tuning-v3"
DATASET_FILE = "train_dataset.json"
LOCAL_DATASET_PATH = f"/content/{DATASET_FILE}"
REMOTE_DATASET_PATH = f"{DATASET_FILE}"

HF_DATASET_REPO_GERMEVAL = "eduhuemar001/sentiment-GermEval2017"
HF_DATASET_REPO_SB10K = "eduhuemar001/sentiment-SB10k"
HF_DATASET_REPO_HOLIDAYCHECK = "eduhuemar001/sentiment-holidaycheck-balanced"

# This is for colab
"""
TRAIN_PATH = "/content/train_dataset.json"
EVAL_PATH  = "/content/eval_dataset.json"
TEST_PATH = "/content/test_dataset.json"
EVAL_JSON = "eval_dataset.json"
"""

# This is for local
from pathlib import Path
BASE_DIR   = Path.cwd() / "content"
TRAIN_PATH = BASE_DIR / "train_dataset.json"
EVAL_PATH  = BASE_DIR / "eval_dataset.json"
TEST_PATH  = BASE_DIR / "test_dataset.json"
EVAL_JSON = "eval_dataset.json"

api = HfApi()

# Check if dataset already exists
try:
    files = list_repo_files(HF_DATASET_REPO_ID, repo_type="dataset")
    dataset_exists = REMOTE_DATASET_PATH in files
except Exception as e:
    print(f"Repo does not exist or could not be listed: {e}")
    files = []
    dataset_exists = False

if dataset_exists:
    print("Loading existing dataset from Hugging Face Hub...")

    dataset_path = hf_hub_download(
        repo_id=HF_DATASET_REPO_ID,
        filename=REMOTE_DATASET_PATH,
        repo_type="dataset",
        local_dir="/content",
        local_dir_use_symlinks=False
    )

    # Read JSON lines
    with open(dataset_path, "r", encoding="utf-8") as f:
        dataset = [json.loads(line) for line in f if line.strip()]

    train_path_hub = hf_hub_download(
        repo_id=HF_DATASET_REPO_ID,
        filename="train_dataset.json",
        repo_type="dataset",
        local_dir="/content",
        local_dir_use_symlinks=False
    )
    eval_path_hub = hf_hub_download(
        repo_id=HF_DATASET_REPO_ID,
        filename=EVAL_JSON,
        repo_type="dataset",
        local_dir="/content",
        local_dir_use_symlinks=False
    )
    with open(train_path_hub, "r", encoding="utf-8") as f:
        dataset = [json.loads(line) for line in f if line.strip()]
    with open(eval_path_hub, "r", encoding="utf-8") as f:
        dataset_eval = [json.loads(line) for line in f if line.strip()]

else:
    print("No existing dataset found. Loading and balancing from sentiment datasets...")

    # Load datasets
    ds_germeval = load_dataset(HF_DATASET_REPO_GERMEVAL, split="train")
    ds_sb10k = load_dataset(HF_DATASET_REPO_SB10K, split="train")
    ds_holidaycheck = load_dataset(HF_DATASET_REPO_HOLIDAYCHECK, split="train")

    # Count sentiment samples
    combined_existing = concatenate_datasets([ds_germeval, ds_sb10k])
    counts = Counter(combined_existing["sentiment"])
    print("Before balancing:", dict(counts))

    max_count = max(counts.values())
    needed_pos = max_count - counts.get("positive", 0)
    needed_neg = max_count - counts.get("negative", 0)

    # Add positive/negative from HolidayCheck
    hc_pos = ds_holidaycheck.filter(lambda x: x["sentiment"] == "positive").shuffle(seed=123).select(range(needed_pos))
    hc_neg = ds_holidaycheck.filter(lambda x: x["sentiment"] == "negative").shuffle(seed=123).select(range(needed_neg))

    # Combine and shuffle
    combined_ds = concatenate_datasets([ds_germeval, ds_sb10k, hc_pos, hc_neg]).shuffle(seed=123)
    final_counts = Counter(combined_ds["sentiment"])
    print("After balancing:", dict(final_counts))

    # Train/test split
    split = combined_ds.train_test_split(test_size=0.2, seed=123)
    train_ds = split["train"]
    test_ds = split["test"]

    # create eval from train (10% of total is 0.125 of train)
    split_tr = train_ds.train_test_split(test_size=0.125, seed=123)
    train_ds = split_tr["train"]
    eval_ds  = split_tr["test"]

    print("\nTrain counts:", Counter(train_ds["sentiment"]))
    print("Eval counts:", Counter(eval_ds["sentiment"]))
    print("Test counts:", Counter(test_ds["sentiment"]))

    # Save function
    def export_dataset(ds, path):
        json_data = []
        with open(path, "w", encoding="utf-8") as f:
            for example in ds:
                if example["review_text"] and example["sentiment"]:
                    item = {
                        "review_text": example["review_text"].strip(),
                        "sentiment": example["sentiment"].strip()
                    }
                    json.dump(item, f, ensure_ascii=False)
                    f.write("\n")
                    json_data.append(item)
        return json_data

    # Save train/eval/test to disk
    print("Saving datasets to disk...")
    dataset       = export_dataset(train_ds, TRAIN_PATH)
    dataset_eval  = export_dataset(eval_ds,  EVAL_PATH)
    export_dataset(test_ds, TEST_PATH)
    print("Uploading datasets to Hugging Face Hub...")

    # Upload train + eval split
    api.create_repo(repo_id=HF_DATASET_REPO_ID, repo_type="dataset", exist_ok=True, token=True)
    api.upload_file(
        path_or_fileobj=TRAIN_PATH,
        path_in_repo="train_dataset.json",
        repo_id=HF_DATASET_REPO_ID,
        repo_type="dataset",
        commit_message="Upload sentiment train split"
    )
    api.upload_file(
        path_or_fileobj=EVAL_PATH,
        path_in_repo=EVAL_JSON,
        repo_id=HF_DATASET_REPO_ID,
        repo_type="dataset",
        commit_message="Upload sentiment eval split"
    )

    # Upload test split
    api.create_repo(repo_id=HF_DATASET_REPO_ID_TEST, repo_type="dataset", exist_ok=True, token=True)
    api.upload_file(
        path_or_fileobj=TEST_PATH,
        path_in_repo="test_dataset.json",
        repo_id=HF_DATASET_REPO_ID_TEST,
        repo_type="dataset",
        commit_message="Upload sentiment test split"
    )

    print("Upload complete.")

train_dataset.json:   0%|          | 0.00/18.0M [00:00<?, ?B/s]

In [ ]:
class SentimentDataset(Dataset):
    def __init__(self, dataset, tokenizer, max_length=512):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.data = []

        # Fixed parts of the prompt
        self.instruction_prefix = (
            "### Instruction:\n"
            "Klassifiziere die Stimmung der folgenden Bewertung als 'positiv', 'neutral' oder 'negativ'.\n\n"
            "### Bewertung:\n"
        )
        self.answer_prefix = "\n\n### Antwort:\n"

        for item in dataset:
            review_text = item["review_text"].strip()
            sentiment = item["sentiment"].strip()

            # Tokenize fixed parts
            prefix_tokens = tokenizer(self.instruction_prefix, add_special_tokens=False)["input_ids"]
            review_tokens = tokenizer(review_text, add_special_tokens=False)["input_ids"]
            answer_prefix_tokens = tokenizer(self.answer_prefix, add_special_tokens=False)["input_ids"]
            label_tokens = tokenizer(sentiment, add_special_tokens=False)["input_ids"]

            # Calculate how many review tokens fit
            reserved = len(prefix_tokens) + len(answer_prefix_tokens) + len(label_tokens)
            max_review_len = self.max_length - reserved
            if max_review_len <= 0:
                continue  # skip if too long

            review_tokens = review_tokens[:max_review_len]

            # Combine all
            input_ids = prefix_tokens + review_tokens + answer_prefix_tokens + label_tokens
            labels = [-100] * (len(prefix_tokens) + len(review_tokens) + len(answer_prefix_tokens)) + label_tokens

            # Pad
            pad_len = self.max_length - len(input_ids)
            input_ids += [tokenizer.pad_token_id] * pad_len
            labels += [-100] * pad_len

            # Sanity check
            if len(input_ids) != self.max_length or len(labels) != self.max_length:
                continue

            self.data.append({
                "input_ids": torch.tensor(input_ids, dtype=torch.long),
                "labels": torch.tensor(labels, dtype=torch.long)
            })

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Build train/eval datasets
train_dataset = SentimentDataset(dataset, tokenizer, max_length=256)
eval_dataset  = SentimentDataset(dataset_eval, tokenizer, max_length=256)

from torch.utils.data import Subset
import numpy as np

EVAL_CAP = 500
rng = np.random.RandomState(42)
idx = rng.choice(len(eval_dataset), size=min(EVAL_CAP, len(eval_dataset)), replace=False)
eval_dataset_small = Subset(eval_dataset, sorted(idx))

Token indices sequence length is longer than the specified maximum sequence length for this model (4289 > 2048). Running this sequence through the model will result in indexing errors

In [ ]:
import os, tempfile, pandas as pd
from huggingface_hub import hf_hub_download

def append_to_hub_csv(repo_id: str, path_in_repo: str, df: pd.DataFrame, repo_type: str = "model"):
    with tempfile.TemporaryDirectory() as td:
        # try to read existing file
        try:
            old = hf_hub_download(
                repo_id=repo_id,
                filename=path_in_repo,
                repo_type=repo_type,
                local_dir=td,
            )
            prev = pd.read_csv(old)
            out = pd.concat([prev, df], ignore_index=True)
        except Exception:
            out = df
        tmp_csv = os.path.join(td, "tmp.csv")
        out.to_csv(tmp_csv, index=False)
        api.upload_file(
            path_or_fileobj=tmp_csv,
            path_in_repo=path_in_repo,
            repo_id=repo_id,
            repo_type=repo_type,
            commit_message=f"[auto] append {os.path.basename(path_in_repo)}",
        )

In [ ]:
from transformers.trainer_callback import TrainerCallback
import optuna

class OptunaReportCallback(TrainerCallback):
    def __init__(self, trial, report_train_loss=False):
        self.trial = trial
        self.report_train_loss = report_train_loss

    # fires when evaluation of model
    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        if metrics and "eval_loss" in metrics:
            step = int(state.global_step)
            self.trial.report(float(metrics["eval_loss"]), step=step)
            # prune bad trials
            if self.trial.study._is_multi_objective() is False and self.trial.should_prune():
                raise optuna.TrialPruned()

    # report training loss snapshots at logging steps
    def on_log(self, args, state, control, logs=None, **kwargs):
        if self.report_train_loss and logs and "loss" in logs:
            step = int(state.global_step)
            self.trial.report(float(logs["loss"]), step=step)

In [ ]:
def objective(trial: optuna.Trial):
    # sample hparams
    hp = {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-2, log=True),
        "warmup_ratio":  trial.suggest_float("warmup_ratio", 0.00, 0.12),
        "lr_scheduler_type": trial.suggest_categorical("lr_scheduler_type", ["linear","cosine"]),
        "lora_dropout":  trial.suggest_float("lora_dropout", 0.0, 0.2),
        "weight_decay":  trial.suggest_float("weight_decay", 0.0, 0.1),
    }

    # build fresh model+trainer per trial
    model = build_model(lora_dropout=hp["lora_dropout"])
    model.gradient_checkpointing_enable()

    # eval every 100 steps
    sig = inspect.signature(TrainingArguments.__init__)
    eval_kwargs = {}
    if "evaluation_strategy" in sig.parameters:
        eval_kwargs["evaluation_strategy"] = "steps"
    elif "eval_strategy" in sig.parameters:
        eval_kwargs["eval_strategy"] = "steps"
    if "eval_steps" in sig.parameters:
        eval_kwargs["eval_steps"] = 100

    # train-loss logging every 10 steps
    log_kwargs = {}
    if "logging_strategy" in sig.parameters:
        log_kwargs["logging_strategy"] = "steps"

    args = TrainingArguments(
        output_dir=f"./runs/trial_{trial.number}",
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=8,
        max_steps=500,
        learning_rate=hp["learning_rate"],
        warmup_ratio=hp["warmup_ratio"],
        weight_decay=hp["weight_decay"],
        lr_scheduler_type=hp["lr_scheduler_type"],
        logging_steps=10,
        save_strategy="no",
        report_to="none",
        fp16=not USE_BF16, # if BF16 unsupported use FP16 # Precision used for math operations (forward, backward, optimizer steps)
        bf16=USE_BF16, # if supported use BF16
        optim="paged_adamw_8bit",
        dataloader_num_workers=0, #dataloader_num_workers=2 on colab
        **eval_kwargs,
        **log_kwargs,
    )

    trainer = Trainer(
        model=model,
        tokenizer=tokenizer,
        args=args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset_small,           # evaluate data
        data_collator=default_data_collator,
        callbacks=[OptunaReportCallback(trial, report_train_loss=False)],
    )

    try:
        trainer.train()
        metrics = trainer.evaluate()
        score = float(metrics["eval_loss"])   # returned to Optuna
    finally:
        # export after trial ends
        rows = []
        for rec in trainer.state.log_history:
            if "loss" in rec:  # training loss snapshots at logging_steps
                step = int(rec.get("step") or rec.get("global_step") or 0)
                rows.append({
                    "trial": trial.number,
                    "step": step,
                    "loss": float(rec["loss"]),
                    **hp
                })

        if rows:
            df = pd.DataFrame(rows)
            append_to_hub_csv(REPO_ID, "logs/step_loss.csv", df, repo_type="model")

        # cleanup VRAM
        del trainer, model
        torch.cuda.empty_cache(); gc.collect()

    return score

In [ ]:
try:
    study = optuna.load_study(study_name=STUDY_NAME, storage=storage)
    print("Resumed existing study.")
except KeyError:
    study = optuna.create_study(
        study_name=STUDY_NAME,
        storage=storage,
        direction="minimize",
        sampler=TPESampler(multivariate=True, group=True, n_startup_trials=8, seed=123),
        pruner=MedianPruner(n_startup_trials=8, n_warmup_steps=200, interval_steps=100),
    )
    print("Created new study.")

C:\Users\marku\anaconda3\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
C:\Users\marku\anaconda3\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``group`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2025-10-12 12:27:58,045] A new study created in RDB with name: tinyllama_tuning_new_20251012_122612

In [ ]:
def push_db_callback(study, trial):
    api.upload_file(
        path_or_fileobj=STUDY_DB,
        path_in_repo=STUDY_KEY,
        repo_id=REPO_ID,
        repo_type="model",
        commit_message=f"[auto] sync DB after trial {trial.number} ({trial.state})",
    )

In [ ]:
study.optimize(objective, n_trials=N_TRIALS, callbacks=[push_db_callback], show_progress_bar=True)

  0%|          | 0/25 [00:00<?, ?it/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

optuna_study.db:   0%|          | 0.00/131k [00:00<?, ?B/s]

max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/135k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/135k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/135k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/135k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/135k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/135k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/139k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/139k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/139k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/139k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/139k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/147k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/152k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/152k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/152k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/152k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/152k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/152k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/156k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/156k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/156k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/156k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

C:\Users\marku\anaconda3\Lib\site-packages\optuna\trial\_trial.py:501: UserWarning: The reported value is ignored because this `step` 500 is already reported.
  warnings.warn(

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/156k [00:00<?, ?B/s]

C:\Users\marku\anaconda3\Lib\site-packages\transformers\training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs

step_loss.csv: 0.00B [00:00, ?B/s]

optuna_study.db:   0%|          | 0.00/156k [00:00<?, ?B/s]

In [ ]:
# Final sync
push_db_callback(study, study.best_trial)

from datetime import datetime
# Collect info
best_result = {
    "timestamp": datetime.now().isoformat(),
    "best_trial_number": study.best_trial.number,
    "best_value": study.best_value,
    "best_params": study.best_params,
}

output_path = "best_optuna_result.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(best_result, f, indent=4)

api.upload_file(
    path_or_fileobj=output_path,
    path_in_repo="optuna/best_optuna_result.json",
    repo_id=REPO_ID,
    repo_type="model",
)
print("Uploaded Optuna results to Hugging Face Hub")

No files have been modified since last commit. Skipping to prevent empty commit.

In [ ]:
print("Best value:", study.best_value)
print("Best params:", study.best_params)
import sys
sys.stdout.flush()

In [ ]:
"""
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)

# 4-bit quantization config (bnb)
# Tip: use float16 on T4/V100; use bfloat16 on A100/H100
compute_dtype = torch.float16  # change to torch.bfloat16 if you're on A100/H100
quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",        # best quality for 4-bit
    bnb_4bit_use_double_quant=True,   # nested quantization saves memory
    bnb_4bit_compute_dtype=compute_dtype
)

# Load model in 4-bit
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    quantization_config=quant_config,
)

# Prepare for k-bit LoRA training (enables input grads, fixes layer norms, etc.)
model = prepare_model_for_kbit_training(model)
model.config.use_cache = False  # important for training (avoids warnings with grad_checkpointing)

# Define LoRA configuration (you can also target more modules for better quality)
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],  # common minimal set; consider adding "k_proj","o_proj","gate_proj","up_proj","down_proj"
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

# Apply LoRA to the quantized model
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
"""

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

trainable params: 1,126,400 || all params: 1,101,174,784 || trainable%: 0.1023